language: node_js
node_js:
- '5.1'
notifications:
  hipchat:
    rooms:
      secure: GaJWpDnyEn+M4bUA3uB29G/elOOoHyxKc0eAgG495oS6rdeV1ZyZlkxv2aWFpOxLwBBMD8wCOV/h5nEL3WUEig8FHqaeGZvNDGuR9sOpXXWJWxTTcXABWsqB+J3NHx0bRFS/6T5MQFTbrasql6Cyph7p92fJaIMqcZqqn95hs8U=
